config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # divice
  devise_for :users, controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/sign_up/confirm', to: 'users/registrations#confirm'
    get 'users/sign_up/complete', to: 'users/registrations#complete'
  end
  # rootパス
  root to: 'books#index'
  # books
  resources :books, only: %i[new create edit update destroy] do
    collection do
      post :confirm
      get :complete
      get :edit_complete
      post :new, path: :new, as: :new, action: :back
    end
    namespace :admin do
      resources :books, only: :index
    end
  end
  # visuals
  resources :visuals do
    collection do
      get :search
    end
  end
  #blogs
  resources :blogs do
    resources :blog_comments, only: :create
    resource :blog_likes, only: %i[create destroy]
  end
  # rooms
  resources :rooms, only: %i[new create]
  # messages
  resources :messages, only: %i[index create destroy]
  # foods
  resources :foods do
    resources :food_comments, only: :create
    resource :food_likes, only: %i[create destroy]
    collection do
      get :search
    end
  end
  # drinks
  resources :drinks do
    resources :drink_comments, only: :create
    resource :drink_likes, only: %i[create destroy]
    collection do
      get :search
    end
  end
  # users
  resources :users, only: :show
end

app/models/visual.rb
# frozen_string_literal: true

class Visual < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :visual_category

  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :visual_category_id, numericality: { other_than: 1 }
    validates :image
  end
end

app/controllers/visuals_controller.rb
# frozen_string_literal: true

class VisualsController < ApplicationController
  before_action :only_admin, only: %i[new create destroy edit update]

  before_action :search_product, only: %i[index search]

  def index
    @visuals = Visual.all.order(visual_category_id: :ASC)
  end

  def search
    @results = @p.result.all
  end

  def new
    @visual = Visual.new
  end

  def create
    @visual = Visual.new(visual_params)
    if @visual.valid?
      @visual.save
    else
      render :new
    end
  end

  def show
    @visual = Visual.find(params[:id])
  end

  def destroy
    @visual = Visual.find(params[:id])
    @visual.destroy
  end

  def edit
    @visual = Visual.find(params[:id])
  end

  def update
    @visual = Visual.find(params[:id])
    if @visual.update(visual_params)
    else
      redirect_to edit_visual(params[:id])
    end
  end

  private

  def visual_params
    params.require(:visual).permit(:image, :visual_category_id).merge(user_id: current_user.id)
  end

  def only_admin
    redirect_to root_path unless current_user.admin?
  end

  def search_product
    @p = Visual.ransack(params[:q])
  end
end

app/helpers/visuals_helper.rb
# frozen_string_literal: true

module VisualsHelper
end

app/views/visuals/_form.html.erb
<div class="visual-render-form">
  <%= form_with model: @visual, local: true do |f| %>
    <div class="form-content">

      <div class="field">
        <%= f.label :image, class: "field-label" %><br />
        <%= f.file_field :image %>
        <% if @visual.errors.include?(:image) %>
          <p style="color: red; margin: 0;">
            <%= @visual.errors.full_messages_for(:image).first %>
          </p>
        <% end %>
        <div id="visual-image-list"></div>
        <%= image_tag @visual.image, id: 'image' if @visual.image.present? %>
      </div>

      <div class="field">
        <%= f.label :visual_category_id, class: "field-labe" %><br />
        <%= f.collection_select :visual_category_id, VisualCategory.all, :id, :name, {class: "visual-category-select"} %>
        <% if @visual.errors.include? (:visual_category_id) %>
          <p style="color: red; margin: 0;">
            <%= @visual.errors.full_messages_for(:visual_category_id).first %>
          </p>
        <% end %>
      </div>
      
      <%= link_to '一覧へ戻る', visuals_path, class: "btn btn-outline-primary mr-3 mt-3" %>
      <%= f.submit '投稿する', class: "btn btn-outline-primary mt-3", data: {
        confirm: "この内容で投稿してもよろしいでしょうか？",
        cancel: "やめる",
        commit: "投稿する"
      }, title: "投稿確認" %>
    </div>
  <% end %>
</div>

app/views/visuals/_radio_button.html.erb
<%= search_form_for @p, url: search_visuals_path do |f| %>
  <%= f.radio_button :visual_category_id_eq, '' %>すべて
  <%= f.radio_button :visual_category_id_eq, '2' %>外観
  <%= f.radio_button :visual_category_id_eq, '3' %>内装
  <%= button_tag type: 'submit',class: 'btn btn-outline-primary btn-sm ml-3' do %>
    <i class="fas fa-search mr-1"></i>検索
  <% end %>
<% end %>

app/views/visuals/_select_box.html.erb
<%= search_form_for @p, url: search_visuals_path do |f| %>
  <%= f.collection_select :visual_category_id_eq, VisualCategory.where.not(id: 1), :id, :name %>
  <%= button_tag type: 'submit',class: 'btn btn-outline-primary btn-sm ml-3' do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/visuals/create.html.erb
<div class="create-content-main">
  <div class="create-content-top">
    <h1 class="create-content-title">投稿完了</h1>
    <ol class="nav">
    <li class="nav-list">1.入力</li>
    <li class="nav-list current">2.完了</li>
  </ol>
  </div>
  
  <div class="create-content">
    <h3 class="create-content-text"><i class="far fa-check-square mr-3"></i>投稿が完了しました</h3>
    <%= link_to '一覧へ戻る', visuals_path, class: "btn btn-outline-danger mt-4" %>
  </div>
</div>

app/views/visuals/destroy.html.erb
<div class="create-content-main">
  <div class="create-content-top">
    <h1 class="create-content-title">削除完了</h1>
  </div>

  <div class="create-content">
    <h3 class="destroy-content-text create-content-text"><i class="fas fa-trash-alt mr-3"></i>投稿の削除が完了しました</h3>
    <%= link_to '一覧へ戻る', visuals_path, class: "btn btn-outline-danger mt-4" %>
  </div>
</div>

app/views/visuals/edit.html.erb
<div class="visual-edit-main">
  <div class="visual-edit-top">
  <h1 class="visual-edit-title">編集画面</h1>
  <ol class="nav">
    <li class="nav-list current">1.入力</li>
    <li class="nav-list">2.完了</li>
  </ol>
  </div>

  <div class="visual-form">
    <%= render 'form' %>
  </div>
</div>

app/views/visuals/index.html.erb
<div class="visual-index-main">
  <div class="visual-index-top">
    <% if current_user.admin? %>
      <%= link_to '新規作成', new_visual_path, class: "btn btn-outline-danger mt-1" %>
    <% end %>
  </div>

  <%#= 検索ボタン %>
  <div class="visual-search-btn">
    <%= render 'visuals/radio_button' %>
  </div>

  <%# 検索セレクトボックス %>
  <div class="select-search">
    <%= render 'visuals/select_box' %>
  </div>

  <div class="visual-index-content container">
    <div class="row justify-content-md-center">
      <% @visuals.each do |visual| %>
        <div class="col-md-4 visual-col">
          <div class="visual-index-image">
            <%= image_tag visual.image.variant(resize: '400x400') %><br />
          </div>
          <% if current_user.admin? %>
            <div class="visual-index-admin">
              <%= link_to '編集', edit_visual_path(visual.id), class: "btn btn-outline-danger btn-sm mr-2" %>
              <%= link_to '削除', visual_path(visual.id), method: :delete,class: "btn btn-outline-danger btn-sm", data: {
                confirm: "こちらの画像を削除してもよろしいでしょうか？",
                cancel: "やめる",
                commit: "削除する"
              }, title: "削除確認" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/visuals/new.html.erb
<div class="visual-new-main">
  <div class="visual-new-top">
    <h1 class="visual-new-title">新規投稿</h1>
    <ol class="nav">
      <li class="nav-list current">1.入力</li>
      <li class="nav-list">2.完了</li>
    </ol>
  </div>

  <div class="visual-form">
    <%= render 'form' %>
  </div>
</div>

app/views/visuals/search.html.erb
<div class="visual-index-main">
  <div class="visual-index-top">
    <% if current_user.admin? %>
      <%= link_to '新規作成', new_visual_path, class: "btn btn-outline-danger mt-1" %>
    <% end %>
  </div>

  <%#= 検索ボタン %>
  <div class="visual-search-btn">
    <%= render 'visuals/radio_button' %>
  </div>

  <%# 検索セレクトボックス %>
  <div class="select-search">
    <%= render 'visuals/select_box' %>
  </div>

  <div class="visual-index-content container">
    <div class="row justify-content-md-center">
      <% @results.each do |visual| %>
        <div class="col-md-4 visual-col">
          <div class="visual-index-image">
            <%= image_tag visual.image.variant(resize: '400x400') %><br />
          </div>
          <% if current_user.admin? %>
            <div class="visual-index-admin">
              <%= link_to '編集', edit_visual_path(visual.id), class: "btn btn-outline-danger btn-sm mr-2" %>
              <%= link_to '削除', visual_path(visual.id), method: :delete,class: "btn btn-outline-danger btn-sm" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/visuals/show.html.erb
<h1>詳細画面</h1>

<%= image_tag @visual.image.variant(resize: '400x400') %>

<% if current_user.admin? %>
  <%= link_to '編集', edit_visual_path(@visual.id) %>
  <%= link_to '削除', visual_path(@visual.id), method: :delete, data: {
    confirm: "こちらの画像を削除してもよろしいでしょうか？",
    cancel: "やめる", 
    commit: "削除する"
  }, title: "削除確認" %>
<% end %>

app/views/visuals/update.html.erb
<div class="create-content-main">
  <div class="create-content-top">
    <h1 class="create-content-title">編集完了</h1>
    <ol class="nav">
      <li class="nav-list">1.入力</li>
      <li class="nav-list current">2.完了</li>
    </ol>
  </div>

  <div class="create-content">
    <h3 class="create-content-text"><i class="far fa-check-square mr-3"></i>編集が完了しました</h3>
    <%= link_to '一覧へ戻る', visuals_path, class: "btn btn-outline-danger mt-4" %>
  </div>
</div>