config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # divice
  devise_for :users, controllers: {
    # omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/sign_up/confirm', to: 'users/registrations#confirm'
    get 'users/sign_up/complete', to: 'users/registrations#complete'
  end
  # rootパス
  root to: 'books#index'
  # books
  resources :books, only: %i[new create edit update destroy] do
    collection do
      post :confirm
      get :complete
      get :edit_complete
      post :new, path: :new, as: :new, action: :back
    end
    namespace :admin do
      resources :books, only: :index
    end
  end
  # visuals
  resources :visuals do
    collection do
      get :search
    end
  end
  #blogs
  resources :blogs do
    resources :blog_comments, only: :create
    resource :blog_likes, only: %i[create destroy]
  end
  # rooms
  resources :rooms, only: %i[new create]
  # messages
  resources :messages, only: %i[index create destroy]
  # foods
  resources :foods do
    resources :food_comments, only: :create
    resource :food_likes, only: %i[create destroy]
    collection do
      get :search
    end
  end
  # drinks
  resources :drinks do
    resources :drink_comments, only: :create
    resource :drink_likes, only: %i[create destroy]
    collection do
      get :search
    end
  end
  # users
  resources :users, only: :show
end

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :food_category

  belongs_to :user
  has_many :food_comments, dependent: :destroy
  has_one_attached :image
  has_many :food_likes, dependent: :destroy

  with_options presence: true do
    # カテゴリー選択は1以外
    validates :food_category_id, numericality: { other_than: 1 }
    # 商品名は40文字以内
    validates :title, length: { minimum: 1, maximum: 40 }
    # 商品詳細は250文字以内
    validates :detail, length: { minimum: 1, maximum: 250 }
    # 値段は半角数字
    validates :price, numericality: { only_integer: true, less_than: 9_999_999 }, format: { with: /\A[0-9]+\z/ }
    # 画像は必須
    validates :image
  end
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

class FoodsController < ApplicationController
  before_action :search_product, only: %i[index search]
  before_action :only_admin, only: %i[new create destroy edit update]

  def index
    @foods = Food.all.order(food_category_id: :ASC)
  end

  def search
    # @results = @p.result.includes(:food_category)
    @results = @p.result.all.order(food_category_id: :ASC)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.valid?
      @food.save
    else
      render :new
    end
  end

  def show
    @food = Food.find(params[:id])
    @comment = FoodComment.new
    @comments = @food.food_comments.includes(:user).order(created_at: :ASC)
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
    else
      render :edit
    end
  end

  private

  def food_params
    params.require(:food).permit(:title, :detail, :price, :image, :food_category_id, :free_food).merge(user_id: current_user.id)
  end

  def search_product
    @p = Food.ransack(params[:q])
  end

  def only_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/foods_helper.rb
# frozen_string_literal: true

module FoodsHelper
end

app/views/foods/_food_like.html.erb
<% if user_signed_in? %>
  <% if current_user.food_likes.find_by(food_id: food.id) %>
      <%= link_to food_food_likes_path(food.id), class: "like-link", method: :DELETE, remote: true do %>
        <i class="fa fa-heart unlike-btn"></i>
      <% end %>
      <%= food.food_likes.count %>
  <% else %>
      <%= link_to food_food_likes_path(food.id), class: "like-link", method: :POST, remote: true do %>
        <i class="fa fa-heart like-btn"></i>
      <% end %>
      <%= food.food_likes.count %>
  <% end %>
<% end %>

app/views/foods/_form.html.erb
<div class="food-render-form">
  <%= form_with model: @food, local: true do |f| %>
    <div class="form-content">
      <div class="field">
        <%= f.label :title, class: "field-label" %><br/>
        <%= f.text_field :title, class: "title-field" %>
        <% if @food.errors.include?(:title) %>
          <p style="color: red; margin: 0;">
            <%= @food.errors.full_messages_for(:title).first %>
          </p>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :detail, class: "field-label" %><br />
        <%= f.text_area :detail, class: "detail-field" %>
        <% if @food.errors.include?(:detail) %>
          <p style="color: red; margin: 0;">
            <%= @food.errors.full_messages_for(:detail).first %>
          </p>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :price, class: "field-label" %><br />
        <span class="price-icon">¥</span><%= f.text_field :price, class: "price-field" %>
        <% if @food.errors.include?(:price) %>
          <p style="color: red; margin: 0;">
            <%= @food.errors.full_messages_for(:price).first %>
          </p>
        <% end %>
      </div>

      <div class="field">
        <%= f.label :food_category_id, class: "field-label" %><br />
        <%= f.collection_select :food_category_id, FoodCategory.all, :id, :name, {class: "food-category-select"} %>
        <% if @food.errors.include?(:food_category_id) %>
          <p style="color: red; margin: 0;">
            <%= @food.errors.full_messages_for(:food_category_id).first %>
          </p>
        <% end %>
      </div>

      <div class="field">
        <p class="check-box-content"><%= f.check_box :free_food, {class: "mr-2"} %>食べ放題を許可する</p>
      </div>

      <div class="field">
        <%= f.label :image, class: "field-label" %><br />
        <%= f.file_field :image %>
        <% if @food.errors.include?(:image) %>
          <p style="color: red; margin: 0;">
            <%= @food.errors.full_messages_for(:image).first %>
          </p>
        <% end %>
      </div>

      <%# プレビュー画像の表示 %>
      <div id='food-image-list'></div>
      <%# 編集画面はこちらに表示 %>
      <%= image_tag @food.image, id: 'image' if @food.image.present? %>

      <div class="submit">
        <%= link_to '戻る', foods_path, class: "btn btn-outline-primary mt-3 mr-3" %>
        <%= f.submit '投稿する', class: "btn btn-outline-primary mt-3", data: {
          confirm: "この内容で投稿してもよろしいでしょうか？",
          cancel: "やめる",
          commit: "投稿する"
        }, title: "投稿確認" %>
      </div>
    </div>
  <% end %>

</div>

app/views/foods/_radio_button.html.erb
<%= search_form_for @p, url: search_foods_path do |f| %>
  <%= f.radio_button :food_category_id_eq, '' %>すべて
  <%= f.radio_button :food_category_id_eq, '2' %>今月のおすすめ
  <%= f.radio_button :food_category_id_eq, '3' %>とりあえず
  <%= f.radio_button :food_category_id_eq, '4' %>サラダ
  <%= f.radio_button :food_category_id_eq, '5' %>一品料理
  <%= f.radio_button :food_category_id_eq, '6' %>串
  <%= f.radio_button :food_category_id_eq, '7' %>焼き物
  <%= f.radio_button :food_category_id_eq, '8' %>海鮮
  <%= f.radio_button :food_category_id_eq, '9' %>主食
  <%= f.radio_button :food_category_id_eq, '10' %>デザート
  <%= f.radio_button :free_food_eq, '1' %>食べ放題
  <%= button_tag type: 'submit',class: 'btn btn-outline-primary btn-sm ml-3' do %>
    <i class="fas fa-search mr-1"></i>検索
  <% end %>
<% end %>

app/views/foods/_select_box.html.erb
<%= search_form_for @p, url: search_foods_path do |f| %>
  <%= f.collection_select :food_category_id_eq, FoodCategory.where.not(id: 1), :id, :name %>
  <%= button_tag type: 'submit',class: 'btn btn-outline-primary btn-sm ml-3' do %>
    <i class="fas fa-search"></i>
  <% end %>
<% end %>

app/views/foods/create.html.erb
<div class="create-content-main">
  <div class="create-content-top">
    <h1 class="create-content-title">投稿完了</h1>
    <ol class="nav">
      <li class="nav-list">1.入力</li>
      <li class="nav-list current">2.完了</li>
    </ol>
  </div>

  <div class="create-content">
    <h3 class="create-content-text"><i class="far fa-check-square mr-3"></i>投稿が完了しました</h3>
    <%= link_to '一覧へ戻る', foods_path, class: "btn btn-outline-danger mt-4" %>
  </div>
</div>

app/views/foods/destroy.html.erb
<div class="create-content-main">
  <div class="create-content-top">
    <h1 class="create-content-title">削除完了</h1>
  </div>

  <div class="create-content">
    <h3 class="create-content-text destroy-content-text"><i class="fas fa-trash-alt mr-3"></i>投稿の削除が完了しました</h3>
    <%= link_to '一覧へ戻る', foods_path, class: "btn btn-outline-danger mt-4" %>
  </div>
</div>

app/views/foods/edit.html.erb
<div class="food-edit-main">
  <div class="create-content-top">
    <h1 class="food-edit-title">編集画面</h1>
    <ol class="nav">
      <li class="nav-list current">1.入力</li>
      <li class="nav-list">2.完了</li>
    </ol>
  </div>

  <%= render 'form' %>
</div>

app/views/foods/index.html.erb
<div class="index-content-main">
  <div class="index-content-top">
    <h1 class="index-content-main-title">フードメニュー</h1>
    <div class="index-content-new">
      <% if current_user.admin? %>
        <%= link_to '新規作成', new_food_path, class: "btn btn-outline-danger" %>
      <% end %>
    </div>
  </div>

  <%# 検索ボタン %>
  <div id="search-area" class="search-btn">
    <%= render 'foods/radio_button' %>
  </div>

  <%# 検索セレクトボックス %>
  <div class="select-search">
    <%= render 'foods/select_box' %>
  </div>

  <%# 投稿一覧 %>
  <div class="index-content-form">
    <% @foods.each do |food| %>
      <div class="index-content">
        <div class="index-content-image">
          <%= link_to food_path(food.id) do %>
            <%= image_tag food.image.variant(resize: '400x400') %>
          <% end %>
          <%# 食べ放題が許可されているメニューにラベル %>
          <% if food.free_food == true %>
            <div class="caption"><span>食べ放題</span></div>
          <% end %>
        </div>

        <%# いいね機能 %>
        <div id="food-<%= food.id %>" class="content-like-btn"> 
          <%= render 'food_like', food: food %>
        </div>
        <%# いいね機能 %>

        <div class="index-content-title">
          <%= food.title %>
        </div>

        <div class="index-content-price">
          ¥<%= food.price %>
        </div>

        <div class="index-content-category">
          <%= food.food_category.name %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="food-new-main">
  <div class="food-new-top">
    <h1 class="food-new-title">新規作成</h1>
    <ol class="nav">
        <li class="nav-list current">1.入力</li>
        <li class="nav-list">2.完了</li>
    </ol>
  </div>

  <%= render 'form' %>
</div>

app/views/foods/search.html.erb
<div class="index-content-main">
  <div class="index-content-top">
    <h1 class="search-title">フードメニュー</h1>
  </div>

  <%# 検索ボタン %>
  <div class="search-btn">
    <%= render 'foods/radio_button' %>
  </div>

  <%# 検索セレクトボックス %>
  <div class="select-search">
    <%= render 'foods/select_box' %>
  </div>

  <%# 検索結果の一覧表示 %>
  <div class="index-content-form">
    <% if @results.length != 0 %>
      <% @results.each do |result| %>
        <div class="index-content">
          

          <div class="index-content-image">
            <%= link_to food_path(result.id) do %>
              <%= image_tag result.image.variant(resize: '400x400') %>
            <% end %>
            <%# 食べ放題が許可されているメニューにラベル %>
            <% if result.free_food == true %>
              <div class="caption"><span>食べ放題</span></div>
            <% end %>
          </div>

          <%#= いいね機能 %>   
          <div id="food-<%= result.id %>" class="content-like-btn"> 
            <%= render 'food_like', food: result %>
          </div>
          
          <div class="index-content-title">
            <%= result.title %>
          </div>

          <div class="index-content-price">
            ¥<%= result.price %>
          </div>

          <div class="index-content-category">
            <%= result.food_category.name %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="non-result-research">
        <h3><i class="fas fa-times-circle mr-2"></i>該当する商品がありませんでした<i class="fas fa-times-circle ml-2"></i></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/foods/show.html.erb
<div class="show-content-main">
  <div class="show-content-left">
    <div class="show-content">

      <div class="show-content-image">
        <%= image_tag @food.image.variant(resize: '400x400') %><br />
        <%# 食べ放題が許可されているメニューにラベル %>
          <% if @food.free_food == true %>
            <div class="caption"><span>食べ放題</span></div>
          <% end %>
      </div>

      <div class="show-content-title">
        <%= @food.title %>
      </div>

      <div class="show-content-detail">
        <%= @food.detail %><br />
      </div>

      <div class="show-content-price">
        ¥<%= @food.price %><br />
      </div>

      <div class="show-content-category">
        <%= @food.food_category.name %>
      </div>

    </div>
    <div class="content-only-admin">
      <%= link_to '一覧へ戻る', foods_path, class: "btn btn-outline-danger btn-lg mr-3" %>
      <% if current_user.admin? %>
        <%= link_to '編集', edit_food_path(params[:id]), class: "btn btn-outline-danger btn-lg mr-3" %>
        <%= link_to '削除', food_path(params[:id]), method: :delete, class: "btn btn-outline-danger btn-lg", data: 
        {confirm: "こちらのフードメニューを削除してもよろしいでしょうか？",
        cancel: "やめる",
        commit: "キャンセルする"}, title: "キャンセル確認" %>
      <% end %>
    </div>
  </div>

  <div class="show-content-right">
    <div class="comment-area">
      <div class="comment-title">
        <i class="fas fa-comments"></i><p class="comment-title-text">comment</p>
      </div>

      <div id="food-comments-area">
        <%= render 'food_comments/index', { comments: @comments } %>
      </div>

      <% if user_signed_in? %>
        <div id="food-comment-create">
          <%= render 'food_comments/comment_form', { comment: @comment, food: @food } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/foods/update.html.erb
<div class="create-content-main">
  <div class="create-content-top">
    <h1 class="create-content-title">編集完了</h1>
    <ol class="nav">
      <li class="nav-list">1.入力</li>
      <li class="nav-list current">2.完了</li>
    </ol>
  </div>

  <div class="create-content">
    <h3 class="create-content-text"><i class="far fa-check-square mr-3"></i>編集が完了しました</h3>
    <%= link_to '詳細へ戻る', food_path(params[:id]), class: "btn btn-outline-danger mt-4" %>
  </div>
</div>